---
# Install firewalld packages

- name: unwanted packages are removed
  package:
    name: "{{ firewalld_packages_remove }}"
    state: absent
  become: true
  when: firewalld_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ firewalld_packages_repos }}"
    state: "{{ firewalld_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ firewalld_packages_prereq }}"
    state: "{{ firewalld_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ firewalld_packages_install }}"
    state: "{{ firewalld_packages_state }}"
  become: true
