---
# Template configuration files for firewalld

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ firewalld_templates_copy }}"
  when: firewalld_copy_templates
